version: '2.2'
services:
  web:
    build: ./
    image: php:7.4-apache
    container_name: ingesta_web
    restart: always
    ports:
     -  8087:80
    volumes:
      - ./:/var/www/html
    links:
     - db:db
    depends_on:
     - db
  db:
    container_name: ingesta_db
    image: mysql:8.0
    restart: always
    #ports:
    # -  33060:3306
    environment:
     - MYSQL_ROOT_PASSWORD=Lg3681Lg
     - MYSQL_USER=ingesta_web
     - MYSQL_PASSWORD=Lg3681Lg
     #- MYSQL_ALLOW_EMPTY_PASSWORD: no
     #- MYSQL_RANDOM_ROOT_PASSWORD: no
     - MYSQL_DATABASE=ingesta_db
    volumes:
     - db-data:/var/lib/mysql
volumes:
  db-data: